openapi: 3.0.0
info:
  title: apitest
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /search:
    post:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: post-searchAPI
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                list:
                  type: array
                  items:
                    type: string
                data:
                  type: object
                  required:
                    - thingy
                  properties:
                    thingy:
                      type: string
                datalist:
                  type: array
                  items:
                    type: object
                    properties:
                      efg:
                        type: number
                      abd:
                        type: string
              required:
                - name
                - age
                - list
                - data
        description: ''
  /user:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-user
      parameters:
        - schema:
            type: string
          in: query
          name: id
          required: true
components:
  schemas: {}
